### ISSUE TITLE
bloxy is not a function. 

### ISSUE THREAD

**Issue by TobiDomi** [nishi7409/ClanLabsV2-OpenSourced#2]
When I ran typed the node code.js , this popped up:
C:\Users\ACER\Desktop\ClanLabs\code.js:11
const bloxyClient = bloxy({
                    ^

TypeError: bloxy is not a function
    at Object.<anonymous> (C:\Users\ACER\Desktop\ClanLabs\code.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

It didnt run the file.

**Comment by karimrir1** [comment]
You may have forgot to install bloxy, Open the cmd in the bot directory then run in the cmd npm install

**Comment by TobiDomi** [comment]
const bloxy = require("bloxy") is in the code already. And I redo everything from scratch, and its not working. I ran the "npm install bloxy" again and again, same text comes up.

**Comment by warbric** [comment]
I'm having the same issue

**Comment by nishi7409** [comment]
im working on the fix rn

**Comment by nishi7409** [comment]
The fix is going to take some time.  Don't have all the time in the world like I used to back in high school :(

**Comment by TobiDomi** [comment]
Sure, I have no problems with that. Just take your time, and thanks for
catching up with me.

**Comment by nishi7409** [comment]
working on fixes now..
